### ISSUE TITLE
comment_mode broken

### ISSUE THREAD

**Issue by jschleic** [kliment/Sprinter#140]
The comment_mode does not work:
Trying to send a comment line starting with ";" does block the communication completely and subsequent commands are ignored. Only a reset can re-activate the controller.
And a comment following a command in the same line is not interpreted; the whole line is currently ignored.

**Comment by kliment** [comment]
Is this in master or experimental?

On Wed, Feb 22, 2012 at 12:39 PM, Joachim Schleicher
reply@reply.github.com
wrote:

**Comment by jschleic** [comment]
I've tried it with master.

But since there are no changes in the logic of get_command() in experimental, I think it could be reproduced in experimental easily. I'll have a look on that.

**Comment by jschleic** [comment]
I experience the same problem concerning comments starting with ";" in experimental (although I had to first fix the Makefile to make the experimental branch compile, see #141)
