### ISSUE TITLE
M203 reprapwiki different to sprinter experimental

### ISSUE THREAD

**Issue by se5a** [kliment/Sprinter#162]
the reprap wiki has M203 as

M203: Record Z adjustment
Example: M203 Z-0.75
This records a Z offset in non-volatile memory in RepRap's microcontroller where it remains active until next set, even when the power is turned off and on again. If the first layer is too close to the bed, you need to effectively move the bed down, so the Z value will be negative. If the nozzle is too far from the bed during the first layer, the Z value should be positive to raise the bed. The maximum adjustment is +/-1.27mm.

Sprinter Experimental it's: 
M203 Temperature monitor for Repetier

Sprinter Main does not have 203 implemented. 

What do other firmwares have M203 as? is reprap wiki page wrong?

**Comment by se5a** [comment]
I got excited when I read the reprap wiki version of M203, it would be very usefull.

**Comment by se5a** [comment]
I'm told:
Marlin.pde: M203 - Set maximum feedrate that your machine can sustain (M203 X200 Y200 Z300 E10000) in mm/sec

so Three different things. awsome.

**Comment by midopple** [comment]
Teacup has no M203 and repetier has M203 as Temperaturmonitor.
At the moment every Firmaware use other function for M203
and what Firmaware use M203 for Z-Offset and what standard is the best?

**Comment by se5a** [comment]
None that I know of use m203 for z-offset so it's possible that the wiki is just plain wrong.

the Z-offset thing is defiantly a feature that would be used frequently. does anyone know if any of the other firmwares actually do this Z-Offset thing?

I'm really more interested in getting that implemented than an argument about what number it should be. (though correcting the wiki and getting it the same as eveyone else is a bonus.)

**Comment by jmgiacalone** [comment]
M203 was used in the eMAKER and RepRapPro version of Sprinter. Marlin uses M206 for the same functionality (although the settings ins't stored in EEPROM), and we are now migrating to this.

So my advice would be to implement this functionality with M206 on Sprinter.

**Comment by midopple** [comment]
Implement in Experimental Version see --> M206 
https://github.com/kliment/Sprinter/commit/3a29ee97d134d5dbb101f6eac0e26746d0e59de1
