### ISSUE TITLE
Z no longer homes

### ISSUE THREAD

**Issue by ddmetzler** [kliment/Sprinter#169]
I downloaded and compiled this version using 023 and my configuration.h out of the 52f7f30 build (could not find any differences).

Using Pronterface (d731aaf) I can move the Z axis, but when I hit the Z-home button it does not attempt to go home.  Reverting to 52f7f30 build fixes it.

**Comment by midopple** [comment]
Hi

Does the Z-Axis no move when homing oder move it in the wrong direction ?
When moveing the z-axis with hand did it go to the right direction ?
Did you copy the configurtion.h or use the newer and set only the values ?

**Comment by ddmetzler** [comment]
The Z axis does not move at all when I hit the home button.

When moving the axis by hand it does move the correct direction.

I copied the configuration.h from the previous version, which I've
attached.  I tried to compare them side-by-side and didn't see a
difference.

I will try updating the configuration.h that came with the software
and update the values.

Thanks,

DougM

On Wed, May 9, 2012 at 1:12 AM, midopple
reply@reply.github.com
wrote:

**Comment by midopple** [comment]
Hi

Is the Option "#define ENDSTOPS_ONLY_FOR_HOMING" aktiv ?
With this option the Endstop is only checked when Homeing is aktiv.

**Comment by ddmetzler** [comment]
ENDSTOPS_ONLY_FOR_HOMING is not active:

//#define ENDSTOPS_ONLY_FOR_HOMING // If defined the endstops will
only be used for homing

on the older builds when the endstop is incorrectly inverted the Z
axis steps down N steps (backoff distance) whereas when the endstop is
set correctly Z will home normally.  I've never seen an instance where
Z doesn't move at all.

In my case all the endstops are inverted:

const bool X_ENDSTOP_INVERT = true;
const bool Y_ENDSTOP_INVERT = true;
const bool Z_ENDSTOP_INVERT = true;

Thanks,

DougM

On Wed, May 9, 2012 at 9:21 AM, midopple
reply@reply.github.com
wrote:

**Comment by ddmetzler** [comment]
This is still an issue in 82bdbc2

with:

#define Z_HOME_DIR -1

it will move (in the wrong direction in my case) when I hit the home button, but it will not stop moving when I trigger the limit sensor (optical).  

with :

#define Z_HOME_DIR 1

It does not move at all.

**Comment by midopple** [comment]
Hi

Did you try to change
--> const bool INVERT_Z_DIR = true; 
and
#define Z_HOME_DIR -1

where is your endstop for Z, at bed level or on the top of the printer

**Comment by ddmetzler** [comment]
That causes it to go the right direction but it does not respond to
triggering the home switch,and the manual control functions via
pronterface are backwards (up is down and down is up).

Caveat that this is the first time I've tried these optical home
switches, so they might not work/be configured correctly.  I have not
installed them yet on x or y so don't know whether they work at all.

My Z endstop is at the top of the printer.

Thanks,

DougM

On Wed, Jun 13, 2012 at 1:26 PM, midopple
reply@reply.github.com
wrote:

**Comment by midopple** [comment]
Then try

#define Z_HOME_DIR 1 --> MAX Endstop
and
in pins.h change from
#define Z_MIN_PIN          20
#define Z_MAX_PIN          -1
to
#define Z_MIN_PIN          -1
#define Z_MAX_PIN          20
20 --> your input number for Endstop

**Comment by ddmetzler** [comment]
Perfect!  Thank you so much for your help. I will close the bug.

DougM

On Wed, Jun 13, 2012 at 1:40 PM, midopple
reply@reply.github.com
wrote:

**Comment by ddmetzler** [comment]
closed per above solution.
