### ISSUE TITLE
Extruder Retraction: Motor does not move

### ISSUE THREAD

**Issue by jschleic** [kliment/Sprinter#170]
With current master d651a6cb90a205b1ec203d756663a9ffdc9b485a filament retraction does not work after some movements. I sliced a file using skeinforge and at some points retraction by 5mm causes the motor to make an approx 800Hz sound. The motor does not move / retract the filament at all but makes some loud noise. Pushing the filament forwards afterwards results in a big blob in the printed part.

Most of the time  retraction works well; but some GCode-combination causes the Extruder to stop retracting.

One of those cases is in the following GCode-Snippet:

```
G90
G92 X77.1 Y98.7 Z0.36 E30.6 ;start from here
; this was line 420
;G1 X75.894 Y97.349 Z0.36 F1440.0 E30.616
;G1 X77.162 Y98.776 Z0.36 F1440.0 E30.6693
G1 X76.862 Y97.914 Z0.36 F1440.0 E30.6948
G1 X76.806 Y97.858 Z0.36 F1440.0 E30.697
G1 F798.0
G1 E25.697 ; motor does not move, approx 800Hz sound (losing steps?!)
```

In Configuration.h I have (manually retracting the extruder at 2700mm/min does work)

```
#define _MAX_FEEDRATE {400, 400, 2, 45}       // (mm/sec)    
```

The experimental branch shows the same behaviour.
6d5a3297f45908bcfa2e10d242d05550a67c123f was working alright.
Any ideas what could cause such a behaviour?

**Comment by jschleic** [comment]
git bisect says:
ee764635a3882722ef0834742c8baf342a3b2ee3 is the first bad commit

**Comment by midopple** [comment]
Hi 

If have change it in the master branch
see https://github.com/kliment/Sprinter/commit/18ad4ffc0e6b446e3475109089e6a0c9a75e2fab
At my printer the G-code now work

Please test it and close the issue if it works, thanks

**Comment by jschleic** [comment]
fix successfully tested and verified.

Thank you!
