### ISSUE TITLE
Compile error with RAPID_OSCILLATION_REDUCTION

### ISSUE THREAD

**Issue by blddk** [kliment/Sprinter#175]
Getting compile error when I comment out RAPID_OSCILLATION_REDUCTION

http://pastebin.com/zpxtyRgT

**Comment by midopple** [comment]
I found the error and corrected in master branch
--> https://github.com/kliment/Sprinter/commit/a63ade8350d8c9be3064a96e6d92ffa6d8d8985c#Sprinter/Configuration.h
