### ISSUE TITLE
Time critical codes being executed too early

### ISSUE THREAD

**Issue by blddk** [kliment/Sprinter#180]
If you send the command to change head bed, hot end, or fan speed, they are executed much longer before they should.

I had this happening to me where the hotend was turned off minutes before the print was finished, resulting in the hot end being too cold to extrude before the print was finished.

Same thing is happening on first layer where the fan is turned on before the first layer is finished, resulting in, where the fan is on, being unable to stick to the bed.

My buffer is also set to 32 steps to prevent it from running out, so the commands are executed a lot before than what they should.

**Comment by midopple** [comment]
see https://github.com/kliment/Sprinter/pull/198/
merged by Kliment
