### ISSUE TITLE
Temp table 7 problems

### ISSUE THREAD

**Issue by rotorit** [kliment/Sprinter#192]
If i choose temp table 7 in either one or both #define THERMISTORHEATER  and #define THERMISTORBED it messes up the temp readings.

Sometimes it reads 5C even w/o any thermistor connected and sometimes it jams up the temp readings completely by freezing after a few seconds. 

(tested on SL 1.3a)

and.. it semes not to be the table it self... because .. when I paste the(content of temp table 7)  table under the "#if (THERMISTORHEATER == 1) || (THERMISTORBED == 1)" it works great.

**Comment by midopple** [comment]
Hi

Please try to add follow line
{1005, 5} --> Last value in Thermistor 7
{1021, 0} --> new last value

**Comment by rotorit** [comment]
nope... still messes up temp reading, and still even if i choose temp teble 7 on only one of the heaters, it allso messes up the temp rading for the one set to temp table 1.

As i said.. if i copy the entire temp table 7 into temp table 1 section.. it works fine(choosing temp table 1 ofcrs) so.. I guess it is not something wrong with the temp table it self... but the flaw is somewhere else in the code.... maybe?

**Comment by rotorit** [comment]
NVM!

I tried Temp table 7 on another SL and on a RAMPS board and both worked fine and then... when i tried the first SL again(for the 7th time or something) it allso worked... so... i guess the first SL had a TEMPorarily allergies for that table or something. 

But the {1021, 0} is a nice one though... You dont want to make the temp rading read 5C when disconnected.. It will mess up the safety feature. 

Thanks for the help.
