### ISSUE TITLE
[experimental] Setting lift in Slic3r causes head crash

### ISSUE THREAD

**Issue by KazW** [kliment/Sprinter#202]
When using the experimental branch and the lift setting is activated in Slic3r, during the lifts, Sprinter will lower the head more and more until it crashed into the bed (over the course of several lifts). When this happens, the Z endstop is triggered, but ignored.

The master branch is unaffected.

**Comment by midopple** [comment]
Hy,
is the option #define ENDSTOPS_ONLY_FOR_HOMING aktiv ?
Can you post your configuration.h over pastebin ?
Maybe the max feedrate is to high for Z

**Comment by KazW** [comment]
@midopple ENDSTOPS_ONLY_FOR_HOMING wouldn't cause the issue described here, only the head crash would be explained (and no, I don't have it set), and my Z feed rate is the default and is optimal for my steppers.

Please re-read the issue (and test for yourself), it's due to Sprinter moving too much in one direction (down) during the lift. The same G-Code and configuration.h in different versions produce different results (master works fine, experimental fails).

**Comment by midopple** [comment]
HI, 

Are you useing the newest Slic3r 0.9.1 ?

I have tested it with Slicer 0.9.1 and see the problem, so there is an issue with the z acc.
To find this bug a lot of debug work had to done.

Thanks

**Comment by midopple** [comment]
Hi,

I have make some changes in experimental, please try the new Version
https://github.com/kliment/Sprinter/commits/experimental/

Thanks

**Comment by KazW** [comment]
Fixed by 3e6cce46ae7d1f3d79fd486761ccd6f28e6d7f3e

This bug affected the lift setting of Slic3r going as far back as 0.8.5-dev or further.
