### ISSUE TITLE
Current version release will not compile

### ISSUE THREAD

**Issue by ellensp** [kliment/Sprinter#213]
In pins.h

The following to pins "TEMP_2_PIN+55, TEMP_BED_PIN+55" have been added to sensitive_pins. 

TEMP_2_PIN is only defined if you have board type 33
TEMP_BED_PIN is not defined anywhere

result. it wont compile like this.

**Comment by midopple** [comment]
Hi, 
I have checked the Master and the Experimentalversion (pins.h) and i cant find this pins in sensitive_pins.

Can you tell me the Linenumber and Version where the compile error is.

Thanks

const int sensitive_pins[] = {0, 1, X_STEP_PIN, X_DIR_PIN, X_ENABLE_PIN, X_MIN_PIN, X_MAX_PIN, Y_STEP_PIN, Y_DIR_PIN, Y_ENABLE_PIN, Y_MIN_PIN, Y_MAX_PIN, Z_STEP_PIN, Z_DIR_PIN, Z_ENABLE_PIN, Z_MIN_PIN, Z_MAX_PIN, E_STEP_PIN, E_DIR_PIN, E_ENABLE_PIN, LED_PIN, PS_ON_PIN, HEATER_0_PIN, HEATER_1_PIN, FAN_PIN, TEMP_0_PIN, TEMP_1_PIN};

**Comment by ellensp** [comment]
I caught Kliment online and I suspect he has fixed it. As you say there is now no mention of TEMP_2_PIN or TEMP_BED_PIN..  Issue is resolved
