### ISSUE TITLE
Problems using 3rd party steppers.

### ISSUE THREAD

**Issue by jpmeyer001** [kliment/Sprinter#216]
I am having a lot of issues using external stepper drivers that require at least a 2μs pulse on the step pin. In addition, my movements are controlled by worm gears so there is a large amount of friction. Is there a #define in the configuration.h file I am missing. Will I have to modify the interrupt functions? Any help would be greatly appreciated. I can post my findings on my project website as well.

**Comment by midopple** [comment]
Hi,
Use the Experimentalversion (also very stable), here is an option in configuration.h

Extended step pulse in microseconds.
Minimum High Time for Stepperpulse at 16 Mhz (E-Axis) is 2,4 us
Minimum High Time for Stepperpulse on X = 6,7 us / Y = 5,6 us / Z = 3,6 us
if you want Stepperpulse like 8 us set the value to 6

#define EXTEND_STEP_PULSE_USEC 0

**Comment by jpmeyer001** [comment]
Thanks a bunch, I really appreciate it. Is there a way to force a square wave output even during acceleration and deceleration? It seems my (very old) stepper drivers requires this to function smoothly.

**Comment by midopple** [comment]
Hi,

This ist not so easy, the stepper pulse is generated in the Interrupt and the interrupt should not wait to long.
So if you wont a squarewave the pulse had to generate with the toggle pin funktion so every step the output change the state.
But this is more programming work.
