### ISSUE TITLE
G28 bug

### ISSUE THREAD

**Issue by caru** [kliment/Sprinter#28]
A variable depending on definition of RAMP_ACCELERATION or EXP_ACCELERATION is used without checking if it's actually defined. This is also not correct, since min_units_per_second is actually the start speed of an accelerated move, not the best speed one can use to home the axis.
In G28: feedrate = min_units_per_second \* 60;
The same for y.

**Comment by ahmetcemturan** [comment]
I agree, homing speeds could be defined in the config file...
I also think that the config file needs to be structured as to must be customized, can be customized etc.
Also sections related Temperature control, acceleration, feedrate..
