### ISSUE TITLE
e_steps_per_unit - problem

### ISSUE THREAD

**Issue by Auzze** [kliment/Sprinter#29]
Changed filment this moring to a diffrent colour, need to re-callabrate the extruder.

PLA brown, it melted at 195C so no problem, Had my steps_mm set at 733, maked off the 110 and it only pushed 35 mm down the tube. In the end I stopped at 3000 steps_mm and decided to re-flash back to an earlier version and the problem was fixed.

I was running the latest Sprinter, version downloaded 16/5/2011
Not 100% sure what the problem is.
Hardware, Prusa wih RAMPS 1.2 with SDRamps
Auzze

**Comment by caru** [comment]
Kliment, do you have any idea what is wrong?
