### ISSUE TITLE
Weird jumping during prints.

### ISSUE THREAD

**Issue by ahmetcemturan** [kliment/Sprinter#32]
I experienced some weird/random ultrafast moves during print.  It looks like it would skip steps but does not.  
Is this normal behaviour because I have the delays enabled?

**Comment by caru** [comment]
I still have the same feeling sometimes, even if I have delays disabled. But I guess that enabling them increments the probability to have such moves.
What I guess is happening, is that as the speed is enforced, sometimes it start deceleration a little after it should, so it terminates the move at a higher speed. Adding a check for that would decrease maximum speed, but maybe that could be added as an option (yes, another option!).
And yes, the configuration file should really be reorganized to be more newbie/user-friendly. A very good example is here: http://forums.reprap.org/read.php?147,81205,85198#msg-85198

**Comment by caru** [comment]
Another thing that will probably help waive the issue, is to not enforce correct speed during deceleration... worth considering/testing

**Comment by caru** [comment]
i think i solved this in experimental, by adding and enabling by default an option to disable heat management during travel moves. Please let me know if this improves things, seems like at changes a lot for me.

**Comment by ahmetcemturan** [comment]
It seems to have gone.  Though I noticed some outbursts of filament during print..  Will have to check and observe to tell more...  Because those fast jumps did not change the print.  Now as the jumpps are gone... can it be that the extruder still thinks they happen?
