### ISSUE TITLE
millis()

### ISSUE THREAD

**Issue by bkubicek** [kliment/Sprinter#39]
Arduino's Millis() has an overflow after 9h32min. If you print something really long, or the machine was left powered before starting a print, this could be problematic.

see e.g. http://www.faludi.com/2007/12/18/arduino-millis-rollover-handling/

Alternatively, there seems to be a possibility to reset the internal millis() counter :
timer0_overflow_count=0 before a linear move might also do trick.

**Comment by kliment** [comment]
Note the article is from 2007. This has now been fixed, and millis will 
overflow after 49 days, as noted in the second comment in the article 
you linked.

**Comment by bkubicek** [comment]
great!
