### ISSUE TITLE
AD595 M105

### ISSUE THREAD

**Issue by bkubicek** [kliment/Sprinter#40]
If using AD595, I had to change two lines to get some serial temperature reading. Apart from that, the temperature conversion routines seemed to work well.

> case 105: // M105
> -        #if (TEMP_0_PIN > -1) || defined (HEATER_USES_MAX6675)
> -        #if (TEMP_0_PIN > -1) || defined (HEATER_USES_MAX6675) || defined (HEATER_USES_AD595)
>        tt = analog2temp(current_raw);
>        #endif
>        #if TEMP_1_PIN > -1
>          bt = analog2tempBed(current_bed_raw);
>        #endif
> -        #if (TEMP_0_PIN > -1) || defined (HEATER_USES_MAX6675)
> -        #if (TEMP_0_PIN > -1) || defined (HEATER_USES_MAX6675) || defined (HEATER_USES_AD595)
>            Serial.print("ok T:");
>            Serial.print(tt); 
>          #if TEMP_1_PIN > -1

**Comment by kliment** [comment]
Can you put this in a pull request?

**Comment by kliment** [comment]
Fixed
