### ISSUE TITLE
Strange pausing  during retraction

### ISSUE THREAD

**Issue by Renosis** [kliment/Sprinter#42]
I am using ramps v1.2 on a mendel prusa, using the latest commit of sprinter (but It happened on earlier commits too). I run repsnapper, but he problem also occurs in pronterface. I have not tried running from sd card, because I don't have that option. I am running ubuntu, my skeinforge version 41. 

I am having this issue, where my bot pauses (x and  y stops moving) during a retraction/pushback. It can be viewed in this video:

http://www.flickr.com/photos/58101887@N02/5867736863/in/photostream

Sorry about the poor video quality, I didn't have my good camera with me today.

When I turn retraction to 1 mm, the pauses are quicker. And if I set retraction mm to 0 the pauses go away completely, but of course this causes ooze.  Noone I talk to in #reprap or #makergearv2 has an answer to the problem, or has even seen it.

**Comment by kliment** [comment]
The pausing needs to be there. It's in the gcode, so it will happen on 
any firmware. The idea is that when you retract, no more filament comes 
out. If you do the un-retract while moving, you get extrusion just 
before it needs to be there, causing blobs just before the point where 
it should resume. Having the retract itself happen during a move is an 
interesting thought though. I'm not sure if it would work. Either way, 
this will require a change in skeinforge, and has nothing to do with 
firmware.

Kliment

**Comment by Renosis** [comment]
Kliment,

I get it, thanks. I spent like five days really troubleshooting this, I feel
really dumb now. I swapped pololus, I changed pins.h to swap X axis for E
axis to make sure it wasn't my hardware. I tried a whole host of skeinforge
and firmware changes. I even tried installing all the software in windows
and trying it from there!

I just wasn't expecting the pauses, the is my first experience with
dimension and my first RepRap. My first printer was a thing-o-matic, and I
was used to the nozzle doing continuous movement.

Thanks so much for the help!

Spencer Renosis

On Sat, Jun 25, 2011 at 2:47 AM, kliment <
reply@reply.github.com>wrote:

> The pausing needs to be there. It's in the gcode, so it will happen on
> any firmware. The idea is that when you retract, no more filament comes
> out. If you do the un-retract while moving, you get extrusion just
> before it needs to be there, causing blobs just before the point where
> it should resume. Having the retract itself happen during a move is an
> interesting thought though. I'm not sure if it would work. Either way,
> this will require a change in skeinforge, and has nothing to do with
> firmware.
> 
> Kliment
> 
> On 06/25/2011 03:34 AM, Renosis wrote:
> 
> > I am using ramps v1.2 on a mendel prusa, using the latest commit of
> > sprinter (but It happened on earlier commits too). I run repsnapper, but he
> > problem also occurs in pronterface. I have not tried running from sd card,
> > because I don't have that option. I am running ubuntu, my skeinforge version
> > 41.
> > 
> > I am having this issue, where my bot pauses (x and  y stops moving)
> > during a retraction/pushback. It can be viewed in this video:
> > 
> > http://www.flickr.com/photos/58101887@N02/5867736863/in/photostream
> > 
> > Sorry about the poor video quality, I didn't have my good camera with me
> > today.
> > 
> > When I turn retraction to 1 mm, the pauses are quicker. And if I set
> > retraction mm to 0 the pauses go away completely, but of course this causes
> > ooze.  Noone I talk to in #reprap or #makergearv2 has an answer to the
> > problem, or has even seen it.
> 
> ## 
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/kliment/Sprinter/issues/42#issuecomment-1437151

## 

Spencer Renosis
Computing Consultant and Network Engineer
renosis@gmail.com
Office (239)259-6343
9081 Ladybug ct.
Fort Myers, fl. 33919
