### ISSUE TITLE
Reverse extruding on restart?

### ISSUE THREAD

**Issue by max-allan** [kliment/Sprinter#53]
Hi,
I'm not sure if this is something I'm doing wrong or something in either the firmware or printrun or maybe skeinforge.
(I don't know which firmware version I have! It was the one dished out at the Bath masterclass.)

Anyway, to reproduce my problem, print something (probably without any filament loaded & heat off).
Let it do a layer or so, then click the "pause" button in printrun.
Optional : Hit Reset in printrun
Then either "restart" if you didn't reset or start a new "print" if you did.

The extruder then tries to suck back everything it just printed. This generally doesn't work and you now need to refeed your filament to start printing again. As well as cancel the print that just started with the filament end hanging loose.
I spent a long time thinking I was doing something wrong in Skeinforge before eventually not changing anything and loading the same gcode and printing again and it noticing that it didn't do what it did when I first loaded the file.
(This makes me think it's nothing to do with Skeinforge settings)

This is a bit annoying when you're trying to tune settings and every time you want to restart a print you need to completely power down the printer (remove USB and main power) or hit the reset switch on the control board. 

It sort of makes sense to do this, I'm using "absolute" setting in "dimension". So I suppose that taking the extruder back to zero makes sense. But I would have thought the "Reset" in printrun could reset the extrude distance to zero...

Thanks,
Max

**Comment by kliment** [comment]
It's very simple. Send a G92 E0 before you start your print (or add it 
to your start.gcode)

This tells the printer that its filament is now at zero, and it then 
happily does what you tell it to.

Normally a reset would set it to zero, but resetting is a bit flaky with 
the sanguinololu.

On that note, I have written a firmware upgrade that makes the printer 
run much smoother. Rodrigo wrote some instructions on how to upgrade 
firmware, you can see them at 
https://github.com/kliment/Sprinter/tree/experimental (scroll down to 
complete beginners guide). It's for Linux but almost everything is the 
same on other platforms. You might want to upgrade at some point.
