### ISSUE TITLE
Current Temp not showing in Repsnapper (357)

### ISSUE THREAD

**Issue by cakeller98** [kliment/Sprinter#99]
Hey,

I just updated from a version of Sprinter (Tonokip) around mid May and found that the Repsnapper "Current Temp" box was being left empty.  I don't have a heated bed, and the feedback from M105 is correctly showing the temp.

I thought at first it was a formatting issue, but turns out it's not.

In the earlier version of the firmware, the output code was:

```
      Serial.print("T:");
      Serial.println(tt); 
```

and if I add those two lines in before the current code... like so:

```
      Serial.print("T:");
      Serial.println(tt); 
    #if (TEMP_0_PIN > -1) || defined (HEATER_USES_MAX6675) || defined HEATER_USES_AD595
        Serial.print("ok T:");
        Serial.print(float(tt));
      #if TEMP_1_PIN > -1 || defined BED_USES_AD595 
        Serial.print(" B:");
        Serial.println(float(bt));
      #else
        Serial.println("");
      #endif
    #else
```

then everything goes back to working... I think repsnapper misses the T:<tt> because of the "ok"

anyway - perhaps for those using Repsnapper V357, we need to add another #define REPSNAPPER_357 ??

and just #ifdef REPSNAPPER_357, then print the temp as before?

**Comment by kliment** [comment]
NOt having the ok there breaks other hosts, and is against the gcode 
definition on the reprap wiki. I don't think anyone should be using 
repsnapper anymore now that pronterface is out. I think you are one of 
the very few to do so.

Kliment

**Comment by cakeller98** [comment]
Sure, that's why it'd be an "#ifdef REPSNAPPER_357" - but hey, I guess if no one is using it (except I am certainly not alone... )

but if I really am one of very few, then sure. 

I did find a few recent posts of people trying to diagnose their hot-end, because the current temp wasn't showing up in Repsnapper... that's kinda bad.  If you know (and aren't a noob) you can click over to the log and see that your temp is ok, but for anyone new... they're kinda like - uh oh, what's wrong?

Repsnapper has worked well for me... I had trouble with pronterface before (May)
I will try it again... last time I had trouble with the pre-requisites on Win 7 x64... Maybe it's simpler now?

**Comment by cakeller98** [comment]
OK - well... I guess it's a lot more straight forward now...

I miss the 3D representation of the GCode that's in Repsnapper ;(  but I'm sure I can get used to this.

**Comment by cakeller98** [comment]
oh sorry, I re-read my initial post... I should have shown my code as:

```
  #ifdef REPSNAPPER_357
  Serial.print("T:");
  Serial.println(tt); 
  #endif REPSNAPPER_357
```

again - if you think NO ONE but me cares... that's fine, I can hack that in each time, myself... or get used to using Pronterface, which - seems a good enough solution....  seems to be missing echoing GCode commands as well as missing a 3D viewing interface... but otherwise :D

**Comment by kliment** [comment]
On 10/03/2011 09:28 AM, Christopher wrote:

> oh sorry, I re-read my initial post... I should have shown my code as:
> 
> ```
>    #ifdef REPSNAPPER_357
>    Serial.print("T:");
>    Serial.println(tt);
>    #endif REPSNAPPER_357
> ```
> 
> again - if you think NO ONE but me cares... that's fine, I can hack that in each time, myself... or get used to using Pronterface, which - seems a good enough solution....  seems to be missing echoing GCode commands as well as missing a 3D viewing interface... but otherwise :D
> 
> Echoing gcodes is in there, but hidden. To activate it, type !self.p.loud=1
> =0 to deactivate.

I'm working on a 3d view at the moment.

Kliment

**Comment by cakeller98** [comment]
Great! :) anyway ... actually am loving Pronterface...

I DONT like being forced to give up something that was working... FEAR CHANGE! :) hahah... but I will generally adapt!

thanks for the tips! I'll add a custom button - thanks again.
